baseURL = 'https://vineetjohn.com'
languageCode = 'en-us'
title = 'Vineet John'
theme = 'hugo-coder'

defaultcontentlanguage = "en"


[markup.highlight]
style = "github-dark"

[params]
  author = "Vineet John"
  info = "Computer Scientist"
  description = "Vineet John's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.svg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/favicon.ico"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/johnvineet/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/vineetjohn/"
[[params.social]]
  name = "Google Scholar"
  icon = "fa-brands fa-google-scholar fa-2x"
  weight = 4
  url = "https://scholar.google.com/citations?user=8sHrLnkAAAAJ&hl=en"

# Menu links
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"
# [[menu.main]]
#   name = "About"
#   weight = 2
#   url = "about/"
